export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";

export const GET_MEALS_SUCCESS = "GET_MEALS_SUCCESS";
export const GET_MEALS_PENDING = "GET_MEALS_PENDING";
export const GET_MEALS_FAIL = "GET_MEALS_FAIL";
export const POST_MEAL_SUCCESS = "POST_MEAL_SUCCESS";
export const POST_MEAL_PENDING = "POST_MEAL_PENDING";
export const POST_MEAL_FAIL = "POST_MEAL_FAIL";
